{{- if .Values.auth }}
apiVersion: v1
data:
  auth: {{ quote .Values.auth }}
kind: Secret
metadata:
  name: ffc-demo-basic-auth
  namespace: {{ quote .Values.namespace }}
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
type: Opaque
{{- end }}
