{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-web.config-map") -}}
{{- define "ffc-demo-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
{{- if .Values.okta.domain }}
  OKTA_DOMAIN: {{ quote .Values.okta.domain }}
{{- end }}
{{- if .Values.pr }}
  SITE_URL: "{{ .Values.container.siteUrl }}-{{ .Values.pr }}.{{ .Values.ingress.server }}"
{{- else }}
  SITE_URL: {{ quote .Values.container.siteUrl }}
{{- end }}
{{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
{{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  REST_CLIENT_TIMEOUT_IN_MILLIS: {{ quote .Values.container.restClientTimeoutMillis }}
  STATIC_CACHE_TIMEOUT_IN_MILLIS: {{ quote .Values.container.staticCacheTimeoutMillis }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  MESSAGE_QUEUE_PORT: {{ quote .Values.container.messageQueuePort }}
  MESSAGE_QUEUE_TRANSPORT: {{ quote .Values.container.messageQueueTransport }}
  CLAIM_QUEUE_ADDRESS: {{ quote .Values.container.claimQueueAddress }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
{{- end -}}
