{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-web.container-secret") -}}
{{- define "ffc-demo-web.container-secret" -}}
stringData:
  COOKIE_PASSWORD: {{ .Values.container.webCookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  CLAIM_QUEUE_USER: {{ .Values.container.claimQueueUser | quote }}
  CLAIM_QUEUE_PASSWORD: {{ .Values.container.claimQueuePassword | quote }}
  {{- if .Values.okta }}
  OKTA_CLIENT_SECRET: {{ .Values.okta.clientSecret | quote }}
  OKTA_CLIENT_ID: {{ .Values.okta.clientId | quote }}
  OKTA_AUTH_SERVER_ID: {{ .Values.okta.authorizationServerId | quote }}
  {{- end }}
{{- end -}}
