{{- if .Values.ingress.alb }}
{{- include "ffc-helm-library.ingress" (list . "ffc-demo-web.ingress-alb") -}}
{{- end }}
{{- define "ffc-demo-web.ingress-alb" -}}
{{- if .Values.ingress.alb }}
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: {{ quote .Values.ingress.alb.securityGroups}}
    alb.ingress.kubernetes.io/certificate-arn: {{ quote .Values.ingress.alb.arn}}
    alb.ingress.kubernetes.io/tags: {{ quote .Values.ingress.alb.tags }}
    external-dns.alpha.kubernetes.io/aws-zone-type-private: "true"
{{- end }}
{{- end -}}
