version: '3.7'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-web:
    networks:
      - default
      - ffc-demo
    ports:
      - "3000:3000"

networks:
  ffc-demo:
    external: true
