version: '3.7'

# This override file should be used when running tests in CI pipelines
# to run tests against app code from the Docker image without binding
# ports to the host machine.

services:
  ffc-demo-web:
    build:
      target: development
    image: ffc-demo-web-development
    command: npm test
    volumes:
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
      - ./package.json:/home/node/package.json
