version: '3'
services:
  mine-support:
    build: .
    image: mine-support
    container_name: mine-support
    command: npm run start:watch
    depends_on:
      - mine-support-redis
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      MINE_SUPPORT_API_GATEWAY: http://mine-support-api-gateway:3001
      REDIS_HOSTNAME: mine-support-redis
    networks:
      - mine-support-redis

  mine-support-redis:
    image: redis
    container_name: mine-support-redis
    networks:
      - mine-support-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


networks:
  mine-support-redis: {}

volumes:
  redis_data:
