version: '3.7'

services:
  ffc-demo-web:
    build:
      context: .
      target: production
    image: ffc-demo-web
    depends_on:
      - ffc-demo-claim-message-queue
    environment:
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      REDIS_HOSTNAME: redis
      OKTA_ENABLED: ${OKTA_ENABLED:-false}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_AUTH_SERVER_ID: ${OKTA_AUTH_SERVER_ID}
      SITE_URL: http://localhost:3000
      MESSAGE_QUEUE_HOST : ffc-demo-claim-message-queue
      MESSAGE_QUEUE_PORT : 5672
      CLAIM_QUEUE_ADDRESS : claim
      CLAIM_QUEUE_USER : artemis
      CLAIM_QUEUE_PASSWORD : artemis

  ffc-demo-claim-message-queue:
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
