apiVersion: v2
description: A Helm chart to deploy the FFC Demo Service sample application to Kubernetes
name: ffc-demo-web
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.2.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
