environment: production
imagePullSecret: myregistrykey
namespace: ffc-demo
service:
  port: 443
  type: NodePort
container:
  allowPrivilegeEscalation: true
  apiGatewayUrl: http://ffc-demo-api-gateway.ffc-demo
  imagePullPolicy: Always
ingress:
  endPoint: ffc-demo-web
  server: ffc-dev.aws-int.defra.cloud
