apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: {{ .Values.containers.service.name }}
  name: {{ .Values.containers.service.name }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.component: {{ .Values.containers.service.name }}
    spec:
      containers:      
      - name: {{ .Values.containers.service.name }}
        image: {{ .Values.containers.service.registry }}{{ .Values.containers.service.image }}:{{ .Values.containers.service.tag }}
        imagePullPolicy: {{ .Values.containers.service.imagePullPolicy }}
        env:                
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: COOKIE_PASSWORD
          valueFrom:
              secretKeyRef:
                key:  cookiePassword
                name: {{ .Release.Name }}-auth
        - name: REDIS_HOSTNAME
          value: {{ .Values.containers.redis.name }}
        - name: MINE_SUPPORT_API_GATEWAY
          value: {{ .Values.containers.service.apiGateway }}
        ports:
        - containerPort: {{ .Values.containers.service.port }}    
      volumes:       
      restartPolicy: {{ .Values.containers.service.restartPolicy }}
status: {}
