apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: {{ .Values.container.name }}
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy: {}
  template:
    metadata:
      labels:
        app.component: {{ .Values.container.name }}
      annotations:
        redeployOnChange: "{{ .Values.container.redeployOnChange }}"
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image }}
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
        command:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
        args:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        env:
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: PORT
          value: "3000"
        - name: COOKIE_PASSWORD
          value: {{ .Values.cookiePassword }}
        - name: REDIS_HOSTNAME
          value: {{ .Values.container.redisname }}
        - name: MINE_SUPPORT_API_GATEWAY
          value: {{ .Values.container.apiGatewayUrl }}
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
            requests:
                memory: {{ .Values.container.requestMemory | quote }}
                cpu: {{ .Values.container.requestCpu | quote }}
            limits:
                memory: {{ .Values.container.limitMemory | quote }}
                cpu: {{ .Values.container.limitCpu | quote }}
      restartPolicy: {{ .Values.container.restartPolicy }}
status: {}
