apiVersion: v1
kind: Service
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  labels:
    app.component: {{ .Values.containers.service.name }}
  name: {{ .Values.containers.service.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.containers.service.servicePort }}
    targetPort: {{ .Values.containers.service.port }}
  selector:
    app.component: {{ .Values.containers.service.name }}
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containers.redis.name }}
spec:
  ports:  
  - port: {{ .Values.containers.redis.port }}
    protocol: TCP
  selector:
    name: {{ .Values.containers.redis.name }}
