environment: development
container:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  #command: ["node"]
  #args: ["--inspect", "index.js"]
  command: ["npx"]
  args: ["nodemon", "--inspect=0.0.0.0", "--ext", "js,njk", "--legacy-watch", "index.js"]
ingress:
  endpoint: skaffold-mine-support
replicaCount: 1
