environment: development
image: mine-support
name: mine-support
auth:
imagePullSecret: 
service:
  port: 80

container:  
  redisname: redis-redis-ha.default
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 50m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  apiGatewayUrl: http://mine-support-api-gateway.default
  restartPolicy: Always
  restClientTimeoutMillis: 20000
  
ingress:
  serviceName: mine-support
  endPoint: mine-support
  server: vividcloudsolutions.co.uk
replicas: 1
minReadySeconds: 5
cookiePassword: passwordpasswordpasswordpasswordpassword

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
