environment: development
containers:
  service:
    name: mine-support
    port: 3000
    servicePort: 80
    registry: ''
    image: mine-support
    tag: latest
    imagePullPolicy: IfNotPresent
    requestMemory: 30Mi
    requestCpu: 10m
    limitMemory: 60Mi
    limitCpu: 40m
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    cookiePassword: ${COOKIE_PASSWORD}
    apiGateway: http://mine-support-api-gateway:3001
    restartPolicy: Always
  redis:
    name: mine-support-redis
    port: 6379        
    image: redis
    imagePullPolicy: IfNotPresent
    tag: latest
    requestMemory: 30Mi
    requestCpu: 10m
    limitMemory: 60Mi
    limitCpu: 40m
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    restartPolicy: Always
ingress:
  serviceName: mine-support
replicas: 2
minReadySeconds: 5
