environment: development
image: mine-support
service:
  port: 80

container:
  name: mine-support
  redisname: redis-redis-ha
  port: 3000
  imagePullPolicy: IfNotPresent
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  apiGatewayUrl: http://mine-support-api-gateway
  apiGatewayPort: 3001
  restartPolicy: Always
ingress:
  serviceName: mine-support
  endPoint: mine-support
replicas: 1
minReadySeconds: 5
cookiePassword: passwordpasswordpasswordpasswordpassword
